#!/bin/sh

OBJECT="$1"
OPERATION="$2"

if [[ $OBJECT == "win10-2" || false ]]; then
	case "$OPERATION" in
	"prepare")
		/etc/nixos/git-repo/hooks/vfio-startup.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
		;;

	"release")
		/etc/nixos/git-repo/hooks/vfio-teardown.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
		;;
	esac
fi
