name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      # - uses: DeterminateSystems/flake-checker-action@main
      # - name: Run `nix build` for tour config
      #   run: nix build '#nixosConfigurations.oscar-tour.config.system.build.toplevel'
      - name: mount big dir in /nix/store
        run: mount -o bind /home/runner/work/nixos-config/nixos-config /nix/store
      - name: Run `nix build` for portable config
        run: nix build '#nixosConfigurations.oscar-portable.config.system.build.toplevel'
