name: CI

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        hostname: ["oscar-portable", "oscar-tour"]
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build system config
        run: nix build '#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'
