name: CI

on:
  push:
  pull_request:

jobs:
  check-systems:
    strategy:
      matrix:
        hostname: ["oscar-portable", "oscar-tour"]
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: maximize build space
        # from https://github.com/easimon/maximize-build-space/blob/master/action.yml
        run: |
          echo "Removing unwanted software... "
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          echo "... done"
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build system config
        run: nix build '#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'

  check-standalone-homemanager:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - printf "" | adduser oscar
      - run: su oscar -c ./homes/oscar/setup-standalone.sh
      - name: re run to make sure it's 'idempotent'
        run: su oscar -c ./homes/oscar/setup-standalone.sh
