name: update-generated-site
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [ gh-pages ]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-generated-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install ghostscript
      - uses: mfinelli/setup-imagemagick@v6
      - name: Generate README.yml
        run: python .github/workflows/pages.py
      - name: Generate latest.png
        run: bash .github/workflows/screenshot-montage.sh
      - name: git commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md latest.png
          git diff --staged --quiet || git commit -m "Update README.md and latest.png"
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
